### ISSUE TITLE
Read Timeout errors - SB6183

### ISSUE THREAD

**Issue by shadowpuck99** [twstokes/arris-scrape#8]
all of a sudden, starting on 08/29 i'm getting read timeout errors.

2022-08-29T13:38:12.457817562Z Error: (<class 'requests.exceptions.ReadTimeout'>, ReadTimeout(ReadTimeoutError("HTTPConnectionPool(host='192.168.100.1', port=80): Read timed out. (read timeout=10)")), <traceback object at 0x7fc552632e00>),

as near as i can tell the modem page is available - but, it's always been slow to respond in a browser.  i did try loading it in a way i thought would be similar to the script (ie, i used w3m cli) and it loaded the page quickly.  so, i'm hesitant to try this, but, is it advisable to try raising the read timeout?

any thoughts or tips or tricks on handling this?

**Comment by shadowpuck99** [comment]
well, strange - it's working fine now.  no idea what, if anything, changed...

**Comment by shadowpuck99** [comment]
well, even more strange - spoke too soon.

it worked for a little bit and then crashed...
i have my scrape interval set at 5 minutes - looks like i got about 20 minutes or 4 reads....same error as before....

**Comment by twstokes** [comment]
👋 @shadowpuck99 - it does sound like your modem's status page is being slow to respond, and [increasing the timeout](https://github.com/twstokes/arris-scrape/blob/5b94f8acce4d258b8982d0261d975a839d5853de/scraper/downloaders/requests.py#L16) is what I'd try. Being able to configure that from the config file would be a great feature to add.

**Comment by shadowpuck99** [comment]
i upped the timeout earlier today and its been stable all day so that's a good sign.
i'm not sure if this is common, but, my 6183 seems rather sensitive to access to the diag page.  that's also why i set my scrape interval further out than normal too.  at any rate - so far it seems to like the increased timeout as well.

**Comment by twstokes** [comment]
Sounds good. I've [made an issue](https://github.com/twstokes/arris-scrape/issues/9) to make that param configurable and will close this one out. Just reopen it if you're still having issues. 👍
